# name: Latest YouTube Videos
# on:
#   schedule:
#     # Runs every day end
#     - cron: '0 0 * * *'
#   workflow_dispatch:

# jobs:
#   update-readme-with-youtube:
#     name: Update this repo's README with latest videos from YouTube
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: gautamkrishnar/blog-post-workflow@master
#         with:
#           comment_tag_name: "YOUTUBE"
#           feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCX7HYec740QGcLGqEcKxBxw"


# name: Update README with YT data

# on:
#   schedule:
#   - cron: '0 0 * * *'
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     name: Update this repo's README with recent YT activity

#     steps:
#       - name: checkput main branch
#         uses: actions/checkout@v3
#       - name: Update this repo's README with recent YT activity
#         uses: DenverCoder1/github-readme-youtube-cards@main
#         with:
#           channel_id: UCX7HYec740QGcLGqEcKxBxw
#           max_videos: 9


name: GitHub Readme YouTube Cards
on:
  schedule:
    # Runs every hour, on the hour
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Allow the job to commit to the repository
    permissions:
      contents: write
    # Run the GitHub Readme YouTube Cards action
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: UCipSxT7a3rn81vGLw9lqRkg
          lang: en
          comment_tag_name: YOUTUBE-CARDS
          youtube_api_key: ${{ secrets.YOUTUBE_API_KEY }} # Configured in Actions Secrets (see Wiki)
          max_videos: 6
          base_url: https://ytcards.demolab.com/
          card_width: 250
          border_radius: 5
          background_color: "#0d1117"
          title_color: "#ffffff"
          stats_color: "#dedede"
          theme_context_light: '{ "background_color": "#ffffff", "title_color": "#24292f", "stats_color": "#57606a" }'
          theme_context_dark: '{ "background_color": "#0d1117", "title_color": "#ffffff", "stats_color": "#dedede" }'
          max_title_lines: 2
          show_duration: true # Requires YouTube API Key (see Wiki)
          author_name: GitHub Actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_message: "docs(readme): Update YouTube cards"
          readme_path: README.md
          output_only: false
          output_type: markdown