name: Update README with Latest YouTube Videos

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Latest Videos
        uses: gautamkrishnar/blog-post-workflow@v2
        with:
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCX7HYec740QGcLGqEcKxBxw"

      - name: Push Changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Updated latest YouTube videos"
          git push
